(rexx "script") ; "","0",""
(rexx "script "x") ; "","Line 1: syntax error, unexpected SYM, expecting '(' or ')' 'x'",""
(rexx "script" (safe)) ; "","0",""
(rexx (safe) "script") ; "","0",""
(rexx "script" (safe) (quiet)) ; "","0",""
(rexx (safe) (quiet) "script") ; "","0",""
(rexx (safe) "script" (quiet)) ; "","0",""
(rexx "script" "x" (safe) (quiet)) ; "","Line 1: syntax error, unexpected STR, expecting '(' or ')' '"x"'",""
(rexx) ; "","Line 1: syntax error, unexpected ')' ')'",""
