(rexx) ; "","Line 1: syntax error, unexpected ')' ')'",""
(rexx "_rx_.rexx") ; "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(rexx ("%s.%s" "_rx_" "rexx")) ; "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(rexx "_rx_") ; "cp ../test/data.rexx.i2 _rx_.rexx","rx _rx_ 0","rm _rx_.rexx"
(rexx "_rx_.rexx" "_rx_") ; "cp ../test/data.rexx.i3 _rx_.rexx","rx _rx_.rexx _rx_ 0","rm -f _rx_"
(rexx "_rx_.rexx" "_rx_" (safe) (quiet)) ; "cp ../test/data.rexx.i3 _rx_.rexx","rx _rx_.rexx _rx_ 0","rm -f _rx_"
(rexx "_rx_.rexx" (confirm 0) (prompt "p") (help "h")) ; "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(rexx "_rx_.rexx" (confirm 1) (prompt "p") (help "h")) ; "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm "AVERAGE") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm "novice") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm 'EXPERT') (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm 0) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm 0 1) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm 1) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm 2) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (confirm) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 0) (rexx "_rx_.rexx" (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm "Expert") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm "Expert" 0) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm "novice") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm 'Average') (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm 0) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm 0 "expert") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm 1) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm 2) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (confirm) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 1) (rexx "_rx_.rexx" (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (confirm "average") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (confirm "expert") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (confirm "novice") (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (confirm 0) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (confirm 1) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (confirm 2) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (confirm) (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","ph0 rx _rx_.rexx 0","rm _rx_.rexx"
(user 2) (rexx "_rx_.rexx" (prompt "p") (help "h")); "cp ../test/data.rexx.i1 _rx_.rexx","rx _rx_.rexx 0","rm _rx_.rexx"
