dist: bionic

language:
    - c

jobs:
    include:
        - stage: Cppcheck
          script: git clone https://github.com/danmar/cppcheck.git && make -C cppcheck && cd src && ../cppcheck/cppcheck --max-ctu-depth=4096 --enable=all --error-exitcode=1 --suppress=missingInclude --suppress=unusedFunction --suppress=ConfigurationNotChecked --suppress=knownConditionTrueFalse --suppress=unmatchedSuppression -U__clang_analyzer__ -UFAIL_FILE_ADDR -UFAIL_FILE_ALLOC -UFAIL_FILE_FOPEN -UFAIL_FILE_DOPEN -UFAIL_FILE_ZERO -UFAIL_LINE_ADDR -UFAIL_LINE_ALLOC -UFAIL_LINE_FOPEN -UFAIL_LINE_DOPEN -UFAIL_LINE_ZERO .
        - stage: Clang scan-build
          script: make -C build clean && scan-build make -C build
        - stage: Test
          script: make -C build smoke || (cat build/err.tmp.* 2> /dev/null && false)
        - stage: Valgrind
          script: make -C build quick || (cat build/err.tmp.* build/leak.tmp.* 2> /dev/null && false)

addons:
  apt:
    packages:
      - valgrind
      - clang-tools
